apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: ${{values.function_id | dump}}
  description: ${{values.description | dump}}
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
spec:
  type: iac
  lifecycle: development
  owner: sourcefuse
